### ISSUE TITLE
vaading 8 version allows user to cursor 'off' grid.

### ISSUE THREAD

**Issue by bsutton** [TatuLund/GridFastNavigation#19] opened 2017-07-16 21:49 UTC
The vaadin 8 version allows a user to use the 'UP' arrow to cursor off the top of the grid.

The problem is that the editor isn't closed when you go up into the header.
Additionally if you cursor up again you are left in no mans land (e.g. no visual focus) and it can take a random number of down arrows to get back to the grid. (i.e. the number of down arrows doesn't equate to the no. of time you up arrowed.

The same problem exists at the bottom of the grid in that you can cursor of the bottom (need to reduce the no. of rows to easily see this).

**Comment by TatuLund** [comment] 2017-07-17 07:11
Yes. This is odd, since I did not notice that behavior in Vaadin 7. Also there seems to be row index client side exceptions at the start, which disappear. I need to investigate this more later, test with Vaadin 8.1 and cross check with our Framework team. I am travelling this week, so I can't do much before weekend.

**Comment by TatuLund** [comment] 2017-07-17 16:18
Oddly, this moving editor off grid phenomenom has disappeared after the latest pull request. There is still the another odd issue of row index exceptions (try ?debug url parameter), which happens in the beggining, but if you keep using it, they disappear. I suspect that it is Grid issue, but I need to dig that deeper later.

**Comment by bsutton** [comment] 2017-07-17 23:03
I will re-test with the latest version and report back my results.

**Comment by bsutton** [comment] 2017-07-25 11:13
I've just re-tested the latest build under chrome and it is still happening.

**Comment by TatuLund** [comment] 2017-07-25 19:18
Yes, you are correct, I can reproduce this too.

**Comment by TatuLund** [comment] 2017-07-26 16:19
I noticed that you had added some if statements to check in EditorStateManager, around rows 244-259 to check wheter we are out of bounds. Actually it should not be necessary, since at row there is if clause which asserts this and if the target row is header, closeEditor is called. This works ok in Vaadin7 version, but for some reason the editor is left open in Vaadin8 version. I will check why.

**Comment by TatuLund** [comment] 2017-07-26 17:47
I did some tests with Vaadin 8.1, and the same problems do happen with it too. I also noticed that getting value of the EditorWidget is working somewhat sporadically.

**Comment by bsutton** [comment] 2017-07-26 21:21
I meant to remove that code. It was an experiment just in case the logic
had a non obvious flaw.
I will do a pull request without the code

**Comment by bsutton** [comment] 2017-07-26 21:22
Do we need a separate 8.1 build or should we do straight to it?

**Comment by TatuLund** [comment] 2017-07-27 05:56
We can go straight to 8.1. I am contacting my colleagues for help with the odd Grid issues. At the moment I haven't found direct cause in add-on code.

**Comment by TatuLund** [comment] 2017-07-28 07:10
I did a commit with couple of small fixes. Now values are read from EditorWidgets properly. However, that does not fix the main issues, which are the following
1) Client side exceptions due row index out of bounds (seem not to originate from add-on, could be also thrown By the other Grid in the UI)
2) Editor not closing when moving to header (also same problem happens when you press enter in the last cell). Add-on calls to close the editor properly, but some reason Grid Editor fails to close.
3) If you have typed more than one character to TextField, and try to set back original value, TextField.setValue(...) does not work properly.

**Comment by TatuLund** [comment] 2017-08-02 11:58
I did some debuging on demo application and found that problem 1. is caused by the message grid, but the root cause is not yet clear for me.

I did some maintenance for Vaadin 7 version and synced changes to this branch too.

**Comment by TatuLund** [comment] 2017-08-02 12:08
Ok. I managed to find workaround for 1. For some reason refreshItem doesn't work, but if use refreshAll, it works.

**Comment by TatuLund** [comment] 2017-08-03 05:38
Issues are fixed in version 2.0.0 and published.

**Closed** 2017-08-03 05:39 UTC
