### ISSUE TITLE
Pressing Esc is not reverting value

### ISSUE THREAD

**Issue by AlexByte** [TatuLund/GridFastNavigation#52] opened 2018-03-13 14:35 UTC
Test with Vaadin 8.3.1
GridFastNavigation version 2.1.10

**Comment by TatuLund** [comment] 2018-03-14 07:10
Thanks for reporting, however this works for me. I.e. I can't replicate the issue.

**Comment by TatuLund** [comment] 2018-03-14 07:42
Which OS and Browser you are using? I tested Windows 10, Edge, IE11, FF & Chrome and they all work ok.

**Comment by AlexByte** [comment] 2018-03-14 13:38
Try this demo https://github.com/AlexByte/gs-crud-with-vaadin

**Comment by TatuLund** [comment] 2018-03-14 14:07
I did first brief check with my demo app, using the extension same way as you do, i.e. https://github.com/AlexByte/gs-crud-with-vaadin/blob/master/complete/src/main/java/hello/VaadinUI.java#L43 just adding it to Grid and not enabling any listeners etc. Still it works. So at least that is not the reason.

It may take a while to check your and setup your test app https://github.com/AlexByte/gs-crud-with-vaadin

**Comment by AlexByte** [comment] 2018-03-14 14:10
Your demo application uses Vaadin 7.

**Comment by TatuLund** [comment] 2018-03-14 14:12
The Vaadin 8 version is here: https://github.com/tatulund/gridfastnavigation/tree/vaadin8

**Comment by AlexByte** [comment] 2018-03-14 14:14
OK

**Comment by AlexByte** [comment] 2018-03-15 11:09
Setting up my test app is easy: `cd complete & mvn jetty run`.

**Comment by AlexByte** [comment] 2018-03-15 11:27
I found out the reason: you set up ValueChangeMode.BLUR for TextField.

**Comment by TatuLund** [comment] 2018-03-15 11:56
Thanks for pointing that out.

**Comment by TatuLund** [comment] 2018-03-15 12:02
I found a fix for this. The blur - focus cycle needed to be added to value setting of the text field. Patch is coming. Thanks for your support.

**Comment by TatuLund** [comment] 2018-03-16 06:33
V7 version was not impacted by this (this was migration regression), this closing.

**Closed by TatuLund** 2018-03-16 06:33 UTC
Labels: bug
