### ISSUE TITLE
How to disable editing column only in one row?

### ISSUE THREAD

**Issue by AlexByte** [TatuLund/GridFastNavigation#55] opened 2018-03-24 00:55 UTC
This code does not work with the plugin:

```
editor.addOpenListener(event -> {
    editorField.setEnabled(event.getBean().isEditingAllowed());
});
```
This is because the plugin resets the state of the fields
https://github.com/TatuLund/GridFastNavigation/blob/55b15d630141e0ac7824d4b974ffb1e7d3fe52c7/GridFastNavigation-addon/src/main/java/org/vaadin/patrik/client/EditorStateManager.java#L460-L463

How can this problem be solved?

**Comment by TatuLund** [comment] 2018-03-26 05:45
Actually the reason is not the one you mentioned. The problem is that editor is already opened when you are trying to change state of the column being editable. This would happen also without GridFastNavigation add-on. However there is solution to this. You need to cancel and re-open the editor.

**Comment by AlexByte** [comment] 2018-03-26 09:46
The code works without using the add-on.

**Comment by AlexByte** [comment] 2018-03-26 10:14
The code works without using the add-on.
>However there is solution to this. You need to cancel and re-open the editor.

This method will only work if you call `notifyEditorOpened()` after `waitForEditorOpen()`.  Also, the focus from the input field will be reset.https://github.com/TatuLund/GridFastNavigation/blob/55b15d630141e0ac7824d4b974ffb1e7d3fe52c7/GridFastNavigation-addon/src/main/java/org/vaadin/patrik/client/EditorStateManager.java#L780-L781

**Comment by AlexByte** [comment] 2018-03-26 11:14
Why do you need to reset all editor widgets to enabled?
https://github.com/TatuLund/GridFastNavigation/blob/55b15d630141e0ac7824d4b974ffb1e7d3fe52c7/GridFastNavigation-addon/src/main/java/org/vaadin/patrik/client/EditorStateManager.java#L460-L463

**Comment by AlexByte** [comment] 2018-03-26 11:54
Why do you need to reset all widgets and then disable required?
https://github.com/TatuLund/GridFastNavigation/blob/55b15d630141e0ac7824d4b974ffb1e7d3fe52c7/GridFastNavigation-addon/src/main/java/org/vaadin/patrik/client/EditorStateManager.java#L460-L468

In my opinion reset all editor widgets to enabled is necessary only for highlighting the text of the cell, when clicking on another cell in the same row in editor.
Why do I need to disable the ones that should be disabald I do not know.

**Comment by TatuLund** [comment] 2018-03-31 10:00
I investigated this a bit more. The true problem seems to be, that logic that is updating status of columns being editable is flawed. I am investigating ways to fix it.

**Comment by TatuLund** [comment] 2018-03-31 15:37
Fixed in versions 2.1.14 & 1.1.9

**Closed by TatuLund** 2018-03-31 15:37 UTC
Labels: bug, question

**Comment by AlexByte** [comment] 2018-04-03 16:49
Why did not you suggest using 

```
fastNavigation.addEditorOpenListener(event -> {
	event.disableColumns(1, 2);
});
```
And why did you delete these methods?

**Comment by TatuLund** [comment] 2018-04-04 05:04
That is true, I was looking this from totally different angle, so I overlooked the possibility and I had not written descriptive enough JavaDoc for that, so I simply forgot. I will return the functionality.

**Comment by TatuLund** [comment] 2018-04-04 06:40
See version 2.1.16

**Comment by AlexByte** [comment] 2018-04-04 13:06
disableColumns(..) can be used to prevent editing of a specific row.
Supports of a way to disable field that does not need to adapt existing code.
