### ISSUE TITLE
If replace numeric field with char, the addon seem not able to recover

### ISSUE THREAD

**Issue by ghost** [TatuLund/GridFastNavigation#39] opened 2017-11-03 10:07 UTC
in one field, I replace 4 with 'r', on purpose ... for testing.   I could not find a way to recover the '4', or undo the 'r'

**Comment by TatuLund** [comment] 2017-11-15 12:13
I cannot reproduce this. E.g. if I use demo application and type character on column "Integer" and then hit Esc, the original value is restored.

**Comment by TatuLund** [comment] 2017-11-18 09:20
I am closing this issue, since I can't reproduce it. If there is new info, it can re-opened.

**Closed by TatuLund** 2017-11-18 09:20 UTC
