### ISSUE TITLE
Pressing Enter changes columns after 2/3 rows

### ISSUE THREAD

**Issue by NiranjanShah** [TatuLund/GridFastNavigation#44] opened 2018-02-19 04:08 UTC
In the Demo Press F2 on Row 3, Col 3 and go on pressing Enter
at some point of time , cursor moves to col4 and pressing Enter again it moves to Col5 and so on.

Can you please check and let us know whether it is intended behaviour based on some condition
or is it a bug.

**Comment by TatuLund** [comment] 2018-02-19 08:09
Cursor moving to col4 is intentional, since col3 has been set uneditable in the demo. Atleast in Vaadin 8 version the enter key goes down by pressing Enter on col4, so it is working correctly since the extension was instantiated as new FastNavigation<>(this, false, true); where the changeColumnOnEnter = false. I also tested another setting FastNavigation<>(this, true, true); and then enter changed the column as it should.

**Comment by TatuLund** [comment] 2018-02-20 06:42
Cannot reproduce

**Closed by TatuLund** 2018-02-20 06:42 UTC
Labels: help wanted, invalid, wontfix
