### ISSUE TITLE
Deleting a row cause grid ui to lock.

### ISSUE THREAD

**Issue by bsutton** [TatuLund/GridFastNavigation#32] opened 2017-08-04 12:23 UTC
I've just made a pull request which enhances the demo grid with a delete button on each row.

I've added the button for two reasons:
1) to show what I think is a good base line for a demo (add/delete and edit rows)
2) to demonstrate a bug I'm coming across in multiple situations.
I finding very easy to hang the grid ui. 
The grid stops responding to clicks so you can edit any more.

To reproduce this run up the demo grid app.
Starting from the bottom delete the bottom two rows.
After you have deleted the two rows the UI will lock up.

I do note a number of errors in the chrome console that whilst need fixing probably arn't the problem.

This error occurs when you click delete the first time.
com.vaadin.client.communication.MessageHandler
SEVERE: Error performing server to client RPC calls
java.lang.IndexOutOfBoundsException: No such logical index: 4
	at Unknown.Eg(org.vaadin.patrik.demo.DemoWidgetSet-0.js)
	at Unknown.Gg(org.vaadin.patrik.demo.DemoWidgetSet-0.js)
	at Unknown.Drd(org.vaadin.patrik.demo.DemoWidgetSet-0.js)

SEVERE: Warning: your widget set seems to be built with a different version than the one used on server. Unexpected behavior may occur.

com.vaadin.client.communication.MessageSender
SEVERE: Trying to start a new request while another is activeUab @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5970TGd @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5508SGd @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:3491YGd @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:3084aHd @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:2116aGb @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:4622WFb @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5498VFb @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:4461m$c @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5362f_c @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5981(anonymous function) @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5612Sh @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:2469Vh @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5128(anonymous function) @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:3588
org.vaadin.patrik.demo.DemoWidgetSet-0.js:5970 Fri Aug 04 22:04:32 GMT+1000 2017 com.vaadin.client.communication.MessageSender
SEVERE: No active requestUab @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5970TGd @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:5508SGd @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:3491YGd @ org.vaadin.patrik.demo.DemoWidgetSet-0.js:3084aHd @ 

WARNING: EditorWidgets.enable: Widget is null

WARNING: Editor bind action is taking longer than expected (5000ms). Does your EditorHandler remember to call success() or fail()?

**Comment by bsutton** [comment] 2017-08-04 13:48
I eventually got a stack trace for the index out of bounds error by running up super dev mode.

**Comment by bsutton** [comment] 2017-08-04 13:54
Grid.java:6354
Grid.java:1433
Grid.java: 1157
EditorConnector:168
EditorConnector:67
ConnectorBundleLoadImpl.java:2221
Method.java:43

Grid.java - line 6349+
 ```
    */
    void focusCell(int rowIndex, int columnIndexDOM) {
        final Range rowRange = Range.between(0, dataSource.size());
        final Range columnRange = Range.between(0, getVisibleColumns().size());

        assert rowRange.contains(
                rowIndex) : "Illegal row index. Should be in range " + rowRange;

```
Variables:
columnIndexDOM:5
columnRange:end=6, start=0
rowIndex=6
rowrange:end=6, start = 0

**Comment by bsutton** [comment] 2017-08-04 14:00
The null widget is being caused by:

```

eXn_g$ | @ | ConsoleLogger.java:32
-- | -- | --
nrn_g$ | @ | SimpleConsoleLogHandler.java:36
Bqn_g$ | @ | Logger.java:312
Aqn_g$ | @ | Logger.java:302
Yqn_g$ | @ | Logger.java:236
Xqn_g$ | @ | Logger.java:227
grn_g$ | @ | Logger.java:164
I$n_g$ | @ | EditorWidgets.java:352
c$n_g$ | @ | EditorStateManager.java:438
U1n_g$ | @ | SpinLock.java:33
(anonymous function) | @ | AnimationSchedulerImplStandard.java:39
OI_g$ | @ | Impl.java:239
RI_g$ | @ | Impl.java:291
(anonymous function) | @ | Impl.java:77

```

and


```
eXn_g$ | @ | ConsoleLogger.java:32
-- | -- | --
nrn_g$ | @ | SimpleConsoleLogHandler.java:36
Bqn_g$ | @ | Logger.java:312
Aqn_g$ | @ | Logger.java:302
Yqn_g$ | @ | Logger.java:236
Xqn_g$ | @ | Logger.java:227
grn_g$ | @ | Logger.java:164
H$n_g$ | @ | EditorWidgets.java:364
c$n_g$ | @ | EditorStateManager.java:443
U1n_g$ | @ | SpinLock.java:33
(anonymous function) | @ | AnimationSchedulerImplStandard.java:39
OI_g$ | @ | Impl.java:239
RI_g$ | @ | Impl.java:291
(anonymous function) | @ | Impl.java:77
```

**Comment by TatuLund** [comment] 2017-08-04 15:44
This is interesting

SEVERE: Warning: your widget set seems to be built with a different version than the one used on server. Unexpected behavior may occur.

This is harmless I think. It is timing issue, that happens sometimes, but seems not to cause trouble

WARNING: EditorWidgets.enable: Widget is null

This error happened in older version, but in the version that was released, it does not occur anymore. It is another indication, that there is old version of the client side running.

WARNING: Editor bind action is taking longer than expected (5000ms). Does your EditorHandler remember to call success() or fail()?

**Comment by TatuLund** [comment] 2017-08-05 19:27
Yes. When I disable the single click opening, things seem to work ok.

**Comment by TatuLund** [comment] 2017-08-06 11:36
I found two alternative approaches to this issues. The other, simple one is just to disable the single click opening. Since I am interested in special renderers (see: https://vaadin.com/directory#!addon/grid-renderers-collection-for-vaadin7), I created custom DeleteButtonRenderer (two phase Button, Delete - Confirm), which also stops click event propagation to Grid. It also works properly. I could include it to add-on. So the root cause really seems to be ButtonRenderer.

**Comment by TatuLund** [comment] 2017-08-06 18:07
Fixed in version 2.1.0

**Closed by TatuLund** 2017-08-06 18:07 UTC

**Comment by bsutton** [comment] 2017-08-06 21:50
So what approach did you take?

My problem with the custom renderer is that this sounds like a generic
problem for buttons on the grid, in that the click shouldn't propergate for
any button.

Having said that the confirm on delete is a nice idea although ideally it
should round trip to the sender and the ask for descriptive text for the
row.

So do we need a generic renderer that stops click propergation?

**Comment by bsutton** [comment] 2017-08-06 23:26
Also I wouldn't view disabling single click as an option as for me at least the single click access to the grid as a key aspect of this add on.

I building a website intended for public use so training isn't an option and 'double click' to edit is not very discoverable for simple casual useers.

**Comment by TatuLund** [comment] 2017-08-07 05:48
I implemented the custom DeleteButtonRenderer. I will include it also to my renderers collection later. I need to have some chats with my colleagues about FW ButtonRenderer. I do not find it particularly good implementation, since it is prone to this kind of side effects.
